# Generated by Django 2.1.3 on 2018-11-16 17:46

import appOkna.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOkna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearticles',
            name='image',
            field=models.FileField(upload_to=appOkna.models.upload_directory, verbose_name='Изображение'),
        ),
    ]
