# Generated by Django 2.1.3 on 2018-11-16 18:58

import appOkna.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appOkna', '0002_auto_20181116_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Контент')),
                ('image', models.FileField(upload_to=appOkna.models.upload_directory, verbose_name='Изображение')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
