# Generated by Django 2.1.3 on 2018-11-16 19:19

import appOkna.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOkna', '0004_auto_20181117_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationarticles',
            name='image',
            field=models.FileField(blank=True, upload_to=appOkna.models.upload_directory, verbose_name='Изображение'),
        ),
    ]
