# Generated by Django 2.1.3 on 2018-11-16 19:32

import appOkna.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOkna', '0005_auto_20181117_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.FileField(upload_to=appOkna.models.upload_directory, verbose_name='Изображение')),
            ],
        ),
    ]
