# Generated by Django 2.1.3 on 2018-11-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOkna', '0008_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный товар?'),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.TextField(default='', max_length=50, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete='CASCADE', to='appOkna.CategoryProduct', verbose_name='Категория товара'),
        ),
    ]
