# Generated by Django 2.1.3 on 2018-11-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOkna', '0009_auto_20181120_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(default='', max_length=10, verbose_name='Стоимость'),
        ),
    ]
