# Generated by Django 2.1.3 on 2018-11-20 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appOkna', '0010_auto_20181120_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='partners',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
