# Generated by Django 2.1.3 on 2018-12-07 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOkna', '0012_auto_20181120_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
