# Generated by Django 2.1.3 on 2019-02-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOkna', '0015_mainpage_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='description',
            field=models.TextField(default='', max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='keywords',
            field=models.TextField(default='', max_length=600, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='title'),
        ),
    ]
