# Generated by Django 2.1.3 on 2019-02-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOkna', '0017_auto_20190204_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='description',
            field=models.TextField(default='Описание товара', max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='keywords',
            field=models.TextField(default='Ключевые слова', max_length=600, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='title',
            field=models.CharField(default='Товар', max_length=100, verbose_name='title'),
        ),
    ]
