# Generated by Django 2.1.3 on 2019-02-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOkna', '0020_auto_20190204_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationarticles',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='informationarticles',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=600, verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='informationarticles',
            name='pagetitle',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='partners',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='partners',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=600, verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='partners',
            name='pagetitle',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='servicearticles',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='servicearticles',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=600, verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='servicearticles',
            name='pagetitle',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='title'),
        ),
    ]
