# Generated by Django 2.1.3 on 2019-02-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOkna', '0021_auto_20190204_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
