# Generated by Django 2.1.3 on 2019-02-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOkna', '0022_categoryproduct_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
