# Generated by Django 2.1.3 on 2019-02-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOkna', '0024_auto_20190208_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='informationarticles',
            name='slug',
            field=models.SlugField(default='', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='slug',
            field=models.SlugField(default='', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='servicearticles',
            name='slug',
            field=models.SlugField(default='', verbose_name='URL'),
        ),
    ]
